### ISSUE TITLE
conventional commits

### ISSUE THREAD

**Issue by ArjixWasTaken** [DereC4/DREaM-Team-App#1]
It appears that you are trying to use conventional commits, but at the same time you don't want to do that?
Is it a commit style you copied from others instead of having learnt?

[Here](https://gist.github.com/levibostian/71afa00ddc69688afebb215faab48fd7) is a nice brief description on what conventional commits are and how to write them.

Most of your commits as of now fall under the `chore:` and `build:` types, yet you use `feat:` (feature) for non-features.
If your changes are not significant enough to guarantee a commit name, then maybe you shouldn't be making a commit.

Or, one other approach is to treat it as a partial commit.

e.g.

`feat: Implemented xyz (1)`
`feat: Implemented xyz (2)`

and you'd do that on a `dev` branch, once finished you can squash all the partial commits together and commit it to the `main` branch

If you are making commits with silly names purely so you don't lose code, I'd suggest using [Git Butler](https://gitbutler.com/)
It can help you make more organized commits w/o the risk of losing progress by not having commited your changes.

**Comment by ArjixWasTaken** [comment]
(sorry for the random lecture, I saw this repo in my feed and ended up here)

**Comment by DereC4** [comment]
whoops that's cool, thanks for your advice. Normally if this were a more professional project i would for sure follow style guidelines more strongly but since this was for a hackathon-styled challenge and we were racing against the clock to deliver our innovation, i did not pay too much attention to the commit messages
